packages:
  - '.'

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

publicHoistPattern:
  - '*'

nodeLinker: hoisted

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - x64
  libc:
    - glibc
